const FETCH_DATA = 'FETCH_DATA';
const MIGRATION_CLUSTER_FETCH_SUCCESS = 'MIGRATION_CLUSTER_FETCH_SUCCESS';
const ADD_CLUSTER_SUCCESS = 'ADD_CLUSTER_SUCCESS';
const ADD_CLUSTER_FAILURE = 'ADD_CLUSTER_FAILURE';
const REMOVE_CLUSTER_SUCCESS = 'REMOVE_CLUSTER_SUCCESS';

export default {
  FETCH_DATA,
  MIGRATION_CLUSTER_FETCH_SUCCESS,
  ADD_CLUSTER_SUCCESS,
  ADD_CLUSTER_FAILURE,
  REMOVE_CLUSTER_SUCCESS,
};
