const REQUEST_TOKEN = "REQUEST_TOKEN";
const RECEIVE_TOKEN = "RECEIVE_TOKEN";
const FAILED_TOKEN = "FAILED_TOKEN";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export default {
  REQUEST_TOKEN,
  RECEIVE_TOKEN,
  FAILED_TOKEN,
  LOGIN,
  LOGOUT
};
