const FETCH_DATA = "FETCH_DATA";
const MIGRATION_PLAN_FETCH_SUCCESS = "MIGRATION_PLAN_FETCH_SUCCESS";
const ADD_PLAN_SUCCESS = "ADD_PLAN_SUCCESS";
const ADD_PLAN_FAILURE = "ADD_PLAN_FAILURE";
const REMOVE_PLAN_SUCCESS = "REMOVE_PLAN_SUCCESS";

export default {
  FETCH_DATA,
  MIGRATION_PLAN_FETCH_SUCCESS,
  ADD_PLAN_SUCCESS,
  ADD_PLAN_FAILURE,
  REMOVE_PLAN_SUCCESS
};
