const FETCH_DATA = 'FETCH_DATA';
const MIGRATION_STORAGE_FETCH_SUCCESS = 'MIGRATION_STORAGE_FETCH_SUCCESS';
const ADD_STORAGE_SUCCESS = 'ADD_STORAGE_SUCCESS';
const ADD_STORAGE_FAILURE = 'ADD_STORAGE_FAILURE';
const REMOVE_STORAGE_SUCCESS = 'REMOVE_STORAGE_SUCCESS';

export default {
  FETCH_DATA,
  MIGRATION_STORAGE_FETCH_SUCCESS,
  ADD_STORAGE_SUCCESS,
  ADD_STORAGE_FAILURE,
  REMOVE_STORAGE_SUCCESS,
};
